# Generated by Django 3.2.2 on 2021-05-09 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
                ('Category_Description', models.TextField(blank=True, null=True)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Code', models.CharField(max_length=100)),
                ('Room_Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unitary Value')),
                ('Offer_Price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unitary Value')),
                ('Vat_Amt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unitary Value')),
                ('Main_Image', models.ImageField(upload_to='images')),
                ('Image_1', models.ImageField(upload_to='images')),
                ('Image_2', models.ImageField(upload_to='images')),
                ('Image_3', models.ImageField(upload_to='images')),
                ('Image_4', models.ImageField(upload_to='images')),
                ('Active', models.BooleanField(default=True)),
                ('User_ID', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.category')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField(max_length=100)),
                ('Date_From', models.DateField(default=datetime.date.today)),
                ('Date_To', models.DateField(default=datetime.date.today)),
                ('Name', models.TextField(max_length=200)),
                ('Phone_No', models.TextField(max_length=20)),
                ('No_of_Person', models.IntegerField()),
                ('No_of_Child', models.IntegerField(blank=True, null=True)),
                ('No_of_Rooms', models.IntegerField()),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=200)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unitary Value')),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField(max_length=100)),
                ('Date_From', models.DateField(default=datetime.date.today)),
                ('Date_To', models.DateField(default=datetime.date.today)),
                ('Name', models.TextField(max_length=200)),
                ('Phone_No', models.TextField(max_length=20)),
                ('No_of_Person', models.IntegerField()),
                ('No_of_Child', models.IntegerField(blank=True, null=True)),
                ('No_of_Rooms', models.IntegerField()),
                ('Payment_Status', models.TextField(max_length=100)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='Advance_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Name', models.CharField(max_length=200)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unitary Value')),
                ('Balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unitary Value')),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.rooms')),
            ],
        ),
    ]
