# Generated by Django 3.2.2 on 2021-05-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_auto_20210509_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Payment_Status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Phone_No',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Phone_No',
            field=models.CharField(max_length=20),
        ),
    ]
