# Generated by Django 3.2.2 on 2021-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0006_auto_20210509_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='Email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
