# Generated by Django 3.2.2 on 2021-05-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0007_reservation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant', models.BooleanField(default=False)),
                ('Purified_Drinking_Water', models.BooleanField(default=False)),
                ('Natural_Environment', models.BooleanField(default=False)),
                ('High_Speed_Wifi', models.BooleanField(default=False)),
                ('Clean_Interiors', models.BooleanField(default=False)),
                ('Free_Parking', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Work_Desk', models.BooleanField(default=False)),
                ('Hairdryer', models.BooleanField(default=False)),
                ('Ironing', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='Bed_Type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='Long_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='No_of_Person',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='Room_Size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='Room_View',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='Room_Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
