# Generated by Django 3.2.2 on 2021-05-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0008_auto_20210510_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='Advance_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Advance_Amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='Balance_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Balance_Amount'),
        ),
        migrations.AddField(
            model_name='booking',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='Email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
